# Site settings
title: Dominikanische Republik
client:
  name: Facettenreiches Karibikparadies
  link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Lassen Sie sich von der Vielfalt der grünen Insel verzaubern, die neben Traumstränden, Merengue und Rum auch Aufregendes für Abenteuerurlauber, intensive Kulturerlebnisse und imposante Naturkulissen zu bieten hat

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/dominikanische-republik" # the subpath of your site, e.g. /blog/
img:     "/de/dominikanische-republik/_assets/img"
css:     "/de/dominikanische-republik/_assets/css"
js:      "/de/dominikanische-republik/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
